<?php
/**
 * @file
 * Code for the USAID Portal Administrator Role feature.
 */

include_once 'portal_administrator_role.features.inc';

/**
 * Implements hook_permission().
 */
function portal_administrator_role_permission() {
  return array(
    'administer user settings' => array(
      'title' => t('Administer User Settings'),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function portal_administrator_role_menu_alter(&$items) {
  foreach ($items as $path => &$item) {
    if (strpos($path, 'admin/config/people') === 0) {
      $item['access callback'] = 'user_access';
      $item['access arguments'] = array('administer user settings');
    }
  }
}

/**
 * Implements hook_modules_enabled().
 */
function portal_administrator_role_modules_enabled($modules) {
  if (in_array($modules, 'data_story_storyteller_role')) {
    user_role_grant_permissions(
      '27274083',
      array('assign storyteller role')
    );
  }
}
