<?php
/**
 * @file
 * Code for the USAID Portal Administrator Role feature.
 */

include_once 'portal_administrator_role.features.inc';

DEFINE('PORTAL_ADMINISTRATOR_ROLE_RID', '27274083');

/**
 * Implements hook_permission().
 */
function portal_administrator_role_permission() {
  return array(
    'administer user settings' => array(
      'title' => t('Administer User Settings'),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function portal_administrator_role_menu_alter(&$items) {
  foreach ($items as $path => &$item) {
    if (strpos($path, 'admin/config/people') === 0) {
      $item['access callback'] = 'user_access';
      $item['access arguments'] = array('administer user settings');
    }
  }
}

/**
 * Implements hook_modules_enabled().
 */
function portal_administrator_role_modules_enabled($modules) {
  if (in_array($modules, 'data_story_storyteller_role')) {
    user_role_grant_permissions(
      PORTAL_ADMINISTRATOR_ROLE_RID,
      array('assign storyteller role')
    );
  }
  if (in_array($modules, 'data_story')) {
    user_role_grant_permissions(
      PORTAL_ADMINISTRATOR_ROLE_RID,
      array(
        'create blog content',
        'delete any blog content',
        'delete own blog content',
        'edit any blog content',
        'edit own blog content',
      )
    );
  }
}

/**
 * Implements hook_form_alter().
 */
function portal_administrator_role_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_cancel_confirm_form') {
    $account = $form['_account']['#value'];
    if (in_array('portal administrator', $account->roles)) {
      $portal_admins = "SELECT uid FROM {users_roles} WHERE rid = '%d'";
      $portal_admins = db_query(
        $portal_admins,
        array(PORTAL_ADMINISTRATOR_ROLE_RID)
      );
      $count = 0;
      foreach ($portal_admins as $portal_admin) {
        $count++;
      }
      if ($count < 2) {
        drupal_set_message(
          t('
            Please assign someone else the portal administrator role before
            deleting this account. There should always be at least one portal
            administrator user on this site.
          '),
          'error'
        );
        drupal_goto('/');
      }
    }
  }
}
